<?php
/**
 * 菜单配置文件
 */

return array (
  0 => 
  array (
    'type' => 'file',
    'name' => 'cesiummapv',
    'title' => '基于球的可视化展示',
    'icon' => 'fa fa-map-o',
    'url' => '',
    'condition' => '',
    'remark' => '',
    'ismenu' => 1,
    'menutype' => NULL,
    'extend' => '',
    'weigh' => 0,
    'sublist' => 
    array (
      0 => 
      array (
        'type' => 'file',
        'name' => 'cesiummapv/config',
        'title' => '配置中心',
        'icon' => 'fa fa-sliders',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/config/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/config/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/config/add',
            'title' => '增加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/config/index',
            'title' => '浏览',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
        ),
      ),
      1 => 
      array (
        'type' => 'file',
        'name' => 'cesiummapv/mapimagery',
        'title' => '地图层管理',
        'icon' => 'fa fa-object-ungroup',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/mapimagery/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/mapimagery/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/mapimagery/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/mapimagery/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/mapimagery/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/mapimagery/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
        ),
      ),
      2 => 
      array (
        'type' => 'file',
        'name' => 'cesiummapv/titleset',
        'title' => '白膜列管理',
        'icon' => 'fa fa-building-o',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/titleset/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/titleset/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/titleset/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/titleset/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/titleset/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/titleset/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
        ),
      ),
      3 => 
      array (
        'type' => 'file',
        'name' => 'cesiummapv/pointeffect',
        'title' => '点坐标效果集',
        'icon' => 'fa fa-bullseye',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/pointeffect/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/pointeffect/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/pointeffect/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/pointeffect/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/pointeffect/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/pointeffect/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
        ),
      ),
      4 => 
      array (
        'type' => 'file',
        'name' => 'cesiummapv/lineseffect',
        'title' => '线效果管理',
        'icon' => 'fa fa-opencart',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/lineseffect/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => 'addtabs',
            'extend' => '',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/lineseffect/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => 'addtabs',
            'extend' => '',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/lineseffect/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => 'addtabs',
            'extend' => '',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/lineseffect/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => 'addtabs',
            'extend' => '',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/lineseffect/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => 'addtabs',
            'extend' => '',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/lineseffect/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => 'addtabs',
            'extend' => '',
            'weigh' => 0,
          ),
        ),
      ),
      5 => 
      array (
        'type' => 'file',
        'name' => 'cesiummapv/modelist',
        'title' => '模型gltf管理',
        'icon' => 'fa fa-cubes',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => NULL,
        'extend' => '',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/modelist/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/modelist/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/modelist/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/modelist/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/modelist/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'cesiummapv/modelist/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'weigh' => 0,
          ),
        ),
      ),
    ),
  ),
);